# MongoDB Configuration
spring:
  profiles:
    active: default
  application:
    name: core-service
  # security:
  #   user:
  #     name: admin
  #     password: admin
  data:
    mongodb:
      database: CIM_DB
      autoIndexCreation: true
  thymeleaf:
    check-template-location: true
# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    root: INFO

fixedRate.in.milliseconds: 600000

---
spring:
  config.activate.on-profile: docker
  data:
    mongodb:
      host: mongo

---
spring:
  config.activate.on-profile: test
  data:
      mongodb:
          uri: ${embedded.mongodb.uri}
          database: CIM_DB
          autoIndexCreation: true