# MongoDB Configuration
spring:
  profiles:
    active: default
  application:
    name: core-service
  # security:
  #   user:
  #     name: admin
  #     password: admin
  data:
    mongodb:
      database: CIM_DB
      autoIndexCreation: true
  thymeleaf:
    check-template-location: true
# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    root: INFO

# Azure Configuration
# azure:
#   tenant-id: your_azure_tenant_id
#   client-id: your_azure_client_id
#   client-secret: your_azure_client_secret

---
spring:
  config.activate.on-profile: docker
  data:
    mongodb:
      host: mongo