# MongoDB Configuration
spring:
  profiles:
    active: default
  application:
    name: edge-service
  main.web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: instance-service-route
        uri: http://localhost:8081
        predicates:
        - Path=/cim/api/v1/instance/**
      - id: lease-service-route
        uri: http://localhost:8082
        predicates:
        - Path=/cim/api/v1/lease/**
      - id: trigger-service-route
        uri: http://localhost:8083
        predicates:
        - Path=/cim/api/v1/trigger/**
  # security:
  #   user:
  #     name: admin
  #     password: admin
# Server Configuration
server:
  port: 8000

# Logging Configuration
logging:
  level:
    root: INFO
    # org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    # org.springframework.cloud.gateway: DEBUG


management.endpoint.gateway.enabled: true
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
  instance:
    preferIpAddress: true
    
---
spring:
  config.activate.on-profile: docker
  cloud:
    gateway:
      routes:
      - id: instance-service-route
        uri: lb://instance-service
        predicates:
        - Path=/cim/api/v1/instance/**
      - id: lease-service-route
        uri: lb://lease-service
        predicates:
        - Path=/cim/api/v1/lease/**
      - id: trigger-service-route
        uri: lb://trigger-service
        predicates:
        - Path=/cim/api/v1/trigger/**
      - id: eureka-route
        uri: lb://composite-service
        predicates:
        - Path=/eureka/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://composite-service:8080/eureka}
